version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: favorite-manager-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://favorite-manager-db:5432/favoritemanager
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_secret
    depends_on:
      - favorite-manager-db

  favorite-manager-db:
    image: postgres:10.23-alpine3.16
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: favoritemanager
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
