version: '3.9'

services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: product_wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
