spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/favoritemanager
    username: my_user
    password: my_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  url: "https://localhost:8081/"
