spring:
  datasource:
    url: jdbc:mysql://<SEU_HOST>:3306/favoritmanager?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <SEU_USUARIO>
    password: <SUA_SENHA>
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

api:
  url: "https://favorit-product-luiza-labs.free.beeceptor.com"

