spring:
  datasource:
    url: jdbc:mysql://localhost:3306/favoritemanager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: my_user
    password: my_secret
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

api:
  url: "https://favorit-product-luiza-labs.free.beeceptor.com"
