CREATE TABLE CLIENT
(
    CLIENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255) NOT NULL,
    EMAIL   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID BIGINT PRIMARY KEY,
    IMAGE   VARCHAR(255),
    PRICE   DOUBLE,
    TITLE   VARCHAR(255) NOT NULL,
    REVIEW_SCORE    VARCHAR(255),
    CLIENT_ID   BIGINT,
    CONSTRAINT FK_PRODUCT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT (CLIENT_ID) ON DELETE CASCADE
);
