
CREATE SCHEMA favorite;

CREATE TABLE favorite.client
(
    CLIENT_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE favorite.product
(
    PRODUCT_ID BIGINT PRIMARY KEY,
    IMAGE VARCHAR(255),
    PRICE DOUBLE PRECISION,
    TITLE VARCHAR(255) NOT NULL,
    REVIEW_SCORE VARCHAR(255),
    CLIENT_ID BIGINT,
    CONSTRAINT FK_PRODUCT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES favorite.client (CLIENT_ID) ON DELETE CASCADE
);
